repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-toml
    - id: check-json
    - id: detect-private-key
    - id: mixed-line-ending
      args: ['--fix=lf']
    - id: requirements-txt-fixer

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
      language_version: python3.8

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.3.0
  hooks:
    - id: mypy
      additional_dependencies: [types-all]
      exclude: ^(docs/|tests/|examples/)
      args: [--ignore-missing-imports]

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      additional_dependencies:
        - flake8-docstrings
        - flake8-bugbear
        - flake8-comprehensions
        - flake8-pytest-style
      exclude: ^(docs/|tests/|examples/)

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
    - id: bandit
      args: ["-c", "pyproject.toml"]
      exclude: ^(tests/|examples/)

- repo: https://github.com/PyCQA/pydocstyle
  rev: 6.3.0
  hooks:
    - id: pydocstyle
      exclude: ^(tests/|examples/)

- repo: https://github.com/asottile/pyupgrade
  rev: v3.4.0
  hooks:
    - id: pyupgrade
      args: [--py38-plus]

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.0
  hooks:
    - id: nbqa-black
      args: ["--line-length=88"]
      additional_dependencies: [black==23.3.0]
    - id: nbqa-isort
      additional_dependencies: [isort==5.12.0]
    - id: nbqa-flake8
      additional_dependencies: [flake8==6.0.0]

ci:
  autofix_commit_msg: "🎨 style: auto-format by pre-commit hooks"
  autoupdate_commit_msg: "⬆️ chore: update pre-commit hooks"
  skip: []
